### ISSUE TITLE
How to log in to it?

### ISSUE THREAD

**Issue by haharay** [harvard-vpal/bridge-adaptivity#250]
by "psycopg2==2.7.3" in requirements_base.txt, some error messages appeared and the installation could not be completed.  change as "psycopg2==2.7.3.2" is ok.

P.S.
I had installed the bridge-adaptivity by the command "make run-local". 
I tried  by "localhost:8008" or "localhost:8008/admin" in browser. 
But I can't find the help about the login username and password in wiki.
Can you give me some help? Thanks.

**Comment by kunanit** [comment]
You'll want to create a initial superuser for django: https://docs.djangoproject.com/en/2.1/intro/tutorial02/#creating-an-admin-user

After that, you can log in to the django admin dashboard and create additional bridge user accounts.

**Comment by haharay** [comment]
thanks. It's ok.

**Comment by mayank-patil** [comment]
created the superuser on the BFA container using the above method
but it does not log into the admin panel after inputting the admin username and password that I created @kunanit

**Comment by idegtiarov** [comment]
@mayank-patil I've did the same recently and didn't find any issue please add any logs or details

**Comment by mayank-patil** [comment]
i am trying to deploy it in AWS ec2  using amazon linux 2
# i used the following command to deploy and install.
sudo yum update -y
sudo yum install docker -y
sudo amazon-linux-extras install docker
sudo service docker start
sudo usermod -a -G docker ec2-user
sudo chkconfig docker on
sudo yum install -y git
sudo reboot
sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/bin/docker-compose
sudo chmod +x /usr/bin/docker-compose
docker-compose version
git clone https://github.com/harvard-vpal/bridge-adaptivity.git
cd bridge-adaptivity/
cd bridge_adaptivity/config/settings/
vim secure_example.py
# added the ["*"] instead of ["localhost"] in the host config
sudo make run-local
#after this i ran
Docker exec -it BFA python manage.py createsuperuser
Username: admin
Email address: admin@example.com
Password: **********
Password (again): *********
Superuser created successfully.
# then i went to the http://ip:8000/admin and also http://ip:8008/admin
# used the user name password i set earlier but i was not logged into the admin panel 
# there was no error that your password is wrong or programming error(which was earlier)
please let me know the gap because if cannot log into the admin panel i cannot login the bridge panel
i also tried the solution mentioned #205  i got same problem if i am using the wrong credentials it is showing the error of wrong credential but with the right credentials it does not show any error but it does let me into the panel as well.

**Comment by mayank-patil** [comment]
@idegtiarov
