### ISSUE TITLE
unable to login to admin panel even after creating superuser!

### ISSUE THREAD

**Issue by mayank-patil** [harvard-vpal/bridge-adaptivity#266]
## i used the following command to deploy and install.
sudo yum update -y
sudo yum install docker -y
sudo amazon-linux-extras install docker
sudo service docker start
sudo usermod -a -G docker ec2-user
sudo chkconfig docker on
sudo yum install -y git
sudo reboot
sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/bin/docker-compose
sudo chmod +x /usr/bin/docker-compose
docker-compose version
git clone https://github.com/harvard-vpal/bridge-adaptivity.git
cd bridge-adaptivity/
cd bridge_adaptivity/config/settings/
vim secure_example.py

added the ["*"] instead of ["localhost"] in the host config
sudo make run-local
## after this i ran
Docker exec -it BFA python manage.py createsuperuser
Username: admin
Email address: admin@example.com
Password: **********
Password (again): *********
Superuser created successfully.

## i think the password i set were working fine but somehow it was not letting me to see the webpage which should be shown after login.

**Comment by idegtiarov** [comment]
Hi @mayank-patil your user was created successfully -- the issue is in the new Chrome security policy.

Several workarounds are available:
 - You can use another browser like Firefox, Edge, etc.
 - You can also use ngrok service as a tunnel to your local service via _https_.
 
And the most interesting option add additional middleware into your settings file - 'django.middleware.security.SecurityMiddleware'
